abstract: PITA Testing Schemes
author: 'Adam Kennedy <cpan@ali.as>, L<http://ali.as/>'
build_requires:
  Cwd: 0
  File::Remove: 0.22
  Module::Build: 0
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.52
license: perl
name: PITA-Scheme
no_index:
  directory:
    - inc
    - t
requires:
  Archive::Extract: 0.07
  Carp: 0
  Config::Tiny: 2.04
  File::Spec: 0.80
  File::Temp: 0
  HTTP::Request::Common: 0
  IPC::Run3: 0.034
  LWP: 5.54
  LWP::UserAgent: 0
  PITA::Report: 0.07
  Params::Util: 0.07
  URI: 0
  perl: 5.005
version: 0.08
