
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.54
distribution_type: module
version: 0.12
name: PITA-Scheme
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  File::Remove: 0.22
  Test::More: 0.47
  Module::Build: 0
  Cwd: 0
requires: 
  perl: 5.005
  Params::Util: 0.10
  Archive::Extract: 0.07
  File::Spec: 0.80
  File::Temp: 0
  IPC::Run3: 0.034
  File::Which: 0
  PITA::XML: 0.15
  Carp: 0
abstract: PITA Testing Schemes
